// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config =  {
    API: {
        GraphQL: {
          endpoint: 'https://lyc5nsovjncx3mnxbw6l2zf7e4.appsync-api.us-west-2.amazonaws.com/graphql',
          region: 'us-west-2',
          defaultAuthMode: 'apiKey',
          apiKey: 'da2-eyuliu6y25caliosszjfkccmbm'
        }
    }
};

export default config;