import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import Image from "next/image";


import { RouterOutputs, api } from "~/utils/api";

const UserInfo = () => {
  const { user } = useUser();

  if (!user) {
    return null;
  }

  return (
    <div className="flex gap-3 w-full">
      <div className="flex gap-3 p-4">
        <Image
          src={user.imageUrl}
          alt="Profile image"
          className="h-12 w-12 rounded-lg"
          width={56}
          height={56}
        />
        <div className="flex flex-col justify-center items-center">
          <div className="  text-slate-400 gap-1 text-xs italic">
            <p>
              <span>{`@${user.username}`}</span>
            </p>
          </div>
          <SignOutButton />
        </div>
      </div>
    </div>)
}

// type MolecleWithAuthor = RouterOutputs["molecule"]["getAll"][number]

const SearchBar = () => {
  return (
    <div className="absolute justify-center items-center">
      <div className="w-full max-w-lg">
        <input
          type="text"
          placeholder="Search for a molecule"
          className="w-full px-4 py-2 mt-2 text-indigo-700 bg-white border rounded-md focus:border-indigo-400 focus:ring-indigo-300 focus:outline-none focus:ring focus:ring-opacity-40" />
      </div>
    </div>
  );
};

export default function Home() {
  const { isLoaded: userLoaded, isSignedIn } = useUser();

  // Start fetching asap
  api.molecule.getAll.useQuery();

  return (
    <>
      <Head>
        <title>X-ray Atlas</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="https://repo.wsu.edu/favicon/icon.svg" />
      </Head>
      <div className="auto flex justify-between top-auto p-4">
        <h1 className="text-2xl font-semibold justify-center">X-ray Atlas</h1>
        <div className="flex fustify-right gap-3">
          {!isSignedIn && (
            <div className="flex justify-center">
              <SignInButton />
            </div>
          )}
          {isSignedIn && <UserInfo />}
        </div>
      </div>
      <main className="absolute top-0 right-0 flex h-screen w-screen justify-center items-center">
        <SearchBar />
      </main>
    </>
  );
}
