import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";

import { api } from "~/utils/api";

export default function Home() {
  const user = useUser();
  const { data } = api.molecule.getAll.useQuery();

  return (
    <>
      <Head>
        <title>X-ray Atlas</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="https://repo.wsu.edu/favicon/icon.svg" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div>
          {!user.isSignedIn && <SignInButton />}
          {!!user.isSignedIn && <SignOutButton />}
        </div>
        < SignIn path="/sign-in" routing="path" signUpUrl="sign-up" />
        <div>
          {data?.map((molecule) => (<div key={molecule.id}>{molecule.materialName}</div>)) ?? "Loading..."}
        </div>
      </main>
    </>
  );
}
