import { type Metadata } from "next";
import { attribution, mission, site } from "~/app/brand";

export const siteMetadata: Metadata = {
  metadataBase: new URL(site.url),
  title: {
    template: `%s | ${site.name}`,
    default: site.name,
  },
  description: mission.seoDescription,
  icons: [{ rel: "icon", url: "https://repo.wsu.edu/favicon/icon.svg" }],
  openGraph: {
    type: "website",
    url: site.url,
    title: mission.ogTitle,
    description: mission.seoDescription,
    siteName: site.name,
    images: [
      {
        url: "https://wpcdn.web.wsu.edu/wp-labs/uploads/sites/945/2017/11/Scattxrayering-Rendering.jpg",
        width: 1200,
        height: 630,
        alt: "X-ray Atlas — open NEXAFS spectroscopy database",
      },
    ],
    locale: "en_US",
  },
  twitter: {
    card: "summary_large_image",
    title: mission.ogTitle,
    description: mission.seoDescription,
    images: ["https://wpcdn.web.wsu.edu/wp-labs/uploads/sites/945/2017/11/Scattxrayering-Rendering.jpg"],
  },
  applicationName: site.applicationName,
  keywords: [
    // Hosting lab
    "WSU",
    "Washington State University",
    "WSU Carbon Lab",
    "WSU Physics",
    "Brian Collins",
    "Collins Research Group",
    // Open / FAIR data
    "Open Data",
    "FAIR Data",
    "Data Repository",
    "Data Archive",
    "Open Science",
    // Research domains
    "Materials science",
    "Materials physics",
    "Atomic Molecular and Optical Physics",
    "Soft Matter Physics",
    "Materials Engineering",
    "Advanced Functional Materials",
    "Organic Semiconductors",
    "Polymer Physics",
    // Spectroscopy — primary
    "NEXAFS",
    "Near-Edge X-ray Absorption Fine Structure",
    "X-ray absorption fine structure",
    "X-ray absorption spectroscopy",
    "EXAFS",
    "XAS",
    "X-ray spectroscopy",
    "X-ray science",
    // Spectroscopy — related techniques
    "X-ray diffraction",
    "X-ray scattering",
    "Resonant Soft X-ray Scattering",
    "RSoXS",
    "PRSoXS",
    "RSoXR",
    "PRSoXR",
    "X-ray crystallography",
    "X-ray imaging",
    // Facilities
    "Advanced Light Source",
    "ALS",
    "National Synchrotron Light Source",
    "NSLS-II",
    "Stanford Synchrotron Radiation Lightsource",
    "SSRL",
    "SLAC National Accelerator Laboratory",
    "SLAC",
    "Advanced Photon Source",
    "APS",
    "Argonne National Laboratory",
    "ANL",
    "Brookhaven National Laboratory",
    "BNL",
    "Lawrence Berkeley National Laboratory",
    "LBNL",
    "Berkeley Lab",
    // Discovery and attribution
    "spectroscopy provenance",
    "citable spectra",
    "DOI data citation",
    "synchrotron data",
    "open spectroscopy database",
  ],
  authors: [
    {
      name: attribution.lab,
      url: attribution.labUrl,
    },
  ],
  robots: {
    index: true,
    follow: true,
  },
  verification: {
    google: "ZkDe5DfUfqbo9aAiISOxS1C-dvhZmMl6SWI9xhSTpkk",
  },
};
