/**
 * Static periodic table layout data for the edge picker modal.
 *
 * Each entry defines an element's symbol, name, atomic number, and its
 * position in the standard 18-column IUPAC periodic table grid (1-indexed
 * row and column). Lanthanide/actinide rows use rows 8-9 at columns 3-17.
 *
 * The grid position determines placement in the `periodic-edge-modal` CSS
 * grid; elements not present in this list are not rendered.
 */

export interface PeriodicElement {
  symbol: string;
  name: string;
  z: number;
  row: number;
  col: number;
}

export const PERIODIC_ELEMENTS: readonly PeriodicElement[] = [
  { symbol: "H", name: "Hydrogen", z: 1, row: 1, col: 1 },
  { symbol: "He", name: "Helium", z: 2, row: 1, col: 18 },
  { symbol: "Li", name: "Lithium", z: 3, row: 2, col: 1 },
  { symbol: "Be", name: "Beryllium", z: 4, row: 2, col: 2 },
  { symbol: "B", name: "Boron", z: 5, row: 2, col: 13 },
  { symbol: "C", name: "Carbon", z: 6, row: 2, col: 14 },
  { symbol: "N", name: "Nitrogen", z: 7, row: 2, col: 15 },
  { symbol: "O", name: "Oxygen", z: 8, row: 2, col: 16 },
  { symbol: "F", name: "Fluorine", z: 9, row: 2, col: 17 },
  { symbol: "Ne", name: "Neon", z: 10, row: 2, col: 18 },
  { symbol: "Na", name: "Sodium", z: 11, row: 3, col: 1 },
  { symbol: "Mg", name: "Magnesium", z: 12, row: 3, col: 2 },
  { symbol: "Al", name: "Aluminum", z: 13, row: 3, col: 13 },
  { symbol: "Si", name: "Silicon", z: 14, row: 3, col: 14 },
  { symbol: "P", name: "Phosphorus", z: 15, row: 3, col: 15 },
  { symbol: "S", name: "Sulfur", z: 16, row: 3, col: 16 },
  { symbol: "Cl", name: "Chlorine", z: 17, row: 3, col: 17 },
  { symbol: "Ar", name: "Argon", z: 18, row: 3, col: 18 },
  { symbol: "K", name: "Potassium", z: 19, row: 4, col: 1 },
  { symbol: "Ca", name: "Calcium", z: 20, row: 4, col: 2 },
  { symbol: "Sc", name: "Scandium", z: 21, row: 4, col: 3 },
  { symbol: "Ti", name: "Titanium", z: 22, row: 4, col: 4 },
  { symbol: "V", name: "Vanadium", z: 23, row: 4, col: 5 },
  { symbol: "Cr", name: "Chromium", z: 24, row: 4, col: 6 },
  { symbol: "Mn", name: "Manganese", z: 25, row: 4, col: 7 },
  { symbol: "Fe", name: "Iron", z: 26, row: 4, col: 8 },
  { symbol: "Co", name: "Cobalt", z: 27, row: 4, col: 9 },
  { symbol: "Ni", name: "Nickel", z: 28, row: 4, col: 10 },
  { symbol: "Cu", name: "Copper", z: 29, row: 4, col: 11 },
  { symbol: "Zn", name: "Zinc", z: 30, row: 4, col: 12 },
  { symbol: "Ga", name: "Gallium", z: 31, row: 4, col: 13 },
  { symbol: "Ge", name: "Germanium", z: 32, row: 4, col: 14 },
  { symbol: "As", name: "Arsenic", z: 33, row: 4, col: 15 },
  { symbol: "Se", name: "Selenium", z: 34, row: 4, col: 16 },
  { symbol: "Br", name: "Bromine", z: 35, row: 4, col: 17 },
  { symbol: "Kr", name: "Krypton", z: 36, row: 4, col: 18 },
  { symbol: "Rb", name: "Rubidium", z: 37, row: 5, col: 1 },
  { symbol: "Sr", name: "Strontium", z: 38, row: 5, col: 2 },
  { symbol: "Y", name: "Yttrium", z: 39, row: 5, col: 3 },
  { symbol: "Zr", name: "Zirconium", z: 40, row: 5, col: 4 },
  { symbol: "Nb", name: "Niobium", z: 41, row: 5, col: 5 },
  { symbol: "Mo", name: "Molybdenum", z: 42, row: 5, col: 6 },
  { symbol: "Tc", name: "Technetium", z: 43, row: 5, col: 7 },
  { symbol: "Ru", name: "Ruthenium", z: 44, row: 5, col: 8 },
  { symbol: "Rh", name: "Rhodium", z: 45, row: 5, col: 9 },
  { symbol: "Pd", name: "Palladium", z: 46, row: 5, col: 10 },
  { symbol: "Ag", name: "Silver", z: 47, row: 5, col: 11 },
  { symbol: "Cd", name: "Cadmium", z: 48, row: 5, col: 12 },
  { symbol: "In", name: "Indium", z: 49, row: 5, col: 13 },
  { symbol: "Sn", name: "Tin", z: 50, row: 5, col: 14 },
  { symbol: "Sb", name: "Antimony", z: 51, row: 5, col: 15 },
  { symbol: "Te", name: "Tellurium", z: 52, row: 5, col: 16 },
  { symbol: "I", name: "Iodine", z: 53, row: 5, col: 17 },
  { symbol: "Xe", name: "Xenon", z: 54, row: 5, col: 18 },
  { symbol: "Cs", name: "Cesium", z: 55, row: 6, col: 1 },
  { symbol: "Ba", name: "Barium", z: 56, row: 6, col: 2 },
  { symbol: "La", name: "Lanthanum", z: 57, row: 8, col: 3 },
  { symbol: "Ce", name: "Cerium", z: 58, row: 8, col: 4 },
  { symbol: "Pr", name: "Praseodymium", z: 59, row: 8, col: 5 },
  { symbol: "Nd", name: "Neodymium", z: 60, row: 8, col: 6 },
  { symbol: "Pm", name: "Promethium", z: 61, row: 8, col: 7 },
  { symbol: "Sm", name: "Samarium", z: 62, row: 8, col: 8 },
  { symbol: "Eu", name: "Europium", z: 63, row: 8, col: 9 },
  { symbol: "Gd", name: "Gadolinium", z: 64, row: 8, col: 10 },
  { symbol: "Tb", name: "Terbium", z: 65, row: 8, col: 11 },
  { symbol: "Dy", name: "Dysprosium", z: 66, row: 8, col: 12 },
  { symbol: "Ho", name: "Holmium", z: 67, row: 8, col: 13 },
  { symbol: "Er", name: "Erbium", z: 68, row: 8, col: 14 },
  { symbol: "Tm", name: "Thulium", z: 69, row: 8, col: 15 },
  { symbol: "Yb", name: "Ytterbium", z: 70, row: 8, col: 16 },
  { symbol: "Lu", name: "Lutetium", z: 71, row: 8, col: 17 },
  { symbol: "Hf", name: "Hafnium", z: 72, row: 6, col: 4 },
  { symbol: "Ta", name: "Tantalum", z: 73, row: 6, col: 5 },
  { symbol: "W", name: "Tungsten", z: 74, row: 6, col: 6 },
  { symbol: "Re", name: "Rhenium", z: 75, row: 6, col: 7 },
  { symbol: "Os", name: "Osmium", z: 76, row: 6, col: 8 },
  { symbol: "Ir", name: "Iridium", z: 77, row: 6, col: 9 },
  { symbol: "Pt", name: "Platinum", z: 78, row: 6, col: 10 },
  { symbol: "Au", name: "Gold", z: 79, row: 6, col: 11 },
  { symbol: "Hg", name: "Mercury", z: 80, row: 6, col: 12 },
  { symbol: "Tl", name: "Thallium", z: 81, row: 6, col: 13 },
  { symbol: "Pb", name: "Lead", z: 82, row: 6, col: 14 },
  { symbol: "Bi", name: "Bismuth", z: 83, row: 6, col: 15 },
  { symbol: "Po", name: "Polonium", z: 84, row: 6, col: 16 },
  { symbol: "At", name: "Astatine", z: 85, row: 6, col: 17 },
  { symbol: "Rn", name: "Radon", z: 86, row: 6, col: 18 },
  { symbol: "Fr", name: "Francium", z: 87, row: 7, col: 1 },
  { symbol: "Ra", name: "Radium", z: 88, row: 7, col: 2 },
  { symbol: "Ac", name: "Actinium", z: 89, row: 9, col: 3 },
  { symbol: "Th", name: "Thorium", z: 90, row: 9, col: 4 },
  { symbol: "Pa", name: "Protactinium", z: 91, row: 9, col: 5 },
  { symbol: "U", name: "Uranium", z: 92, row: 9, col: 6 },
  { symbol: "Np", name: "Neptunium", z: 93, row: 9, col: 7 },
  { symbol: "Pu", name: "Plutonium", z: 94, row: 9, col: 8 },
  { symbol: "Am", name: "Americium", z: 95, row: 9, col: 9 },
  { symbol: "Cm", name: "Curium", z: 96, row: 9, col: 10 },
  { symbol: "Bk", name: "Berkelium", z: 97, row: 9, col: 11 },
  { symbol: "Cf", name: "Californium", z: 98, row: 9, col: 12 },
  { symbol: "Es", name: "Einsteinium", z: 99, row: 9, col: 13 },
  { symbol: "Fm", name: "Fermium", z: 100, row: 9, col: 14 },
];
